# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6cd07a10a45e166519b513d31df3ae8b62012e4bb41a102e3a48a12719596b901277ea57767e801e12a6c5f6291c7155267db3afaa78b542d13562f01cb8a7

test:
  secret_key_base: dd96f4b0d83cf8853b3e202857284eacf73e826a341244349524b85627d3395b45805c438fba026ba24eeac42b98b790f5551ff5df2fdd94fe5ebc41d2df4e97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
